server:
  port: 9200
file:
  ip: localhost
spring:
  account: '###@qq.com'
  mail:
    host: "smtp.qq.com"
    port: 25
    username: ###@qq.com
    password: ###
    default-encoding: utf-8
    test-connection: true
    properties:
      connection-timeout: 500
  security:
    jwt:
      key: 'Rainy-Heights'
      expire: 72
    user:
      name: 123
      password: 123
    filter:
      order: -120
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  data:
    redis:
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/bootdemo
    password: 123456
    username: root
url: 127.0.0.1
logging:
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
